project_id: '574887'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
files:
  - source: /i18n/es/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/Training-Manual/**/*
    ignore:
      - /**/*.png
      - /**/*.jpeg /**/*.jpg /**/*.json
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
