project_id: '574887'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1

files: [
    {
      "source": /docs/**/*.*,
      "translation": /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%,
      "skip_untranslated_files": true,
    },
  ]
